storacha/reads

- packages/edge-gateway/README.md
- packages/edge-gateway/package.json
- packages/edge-gateway/src/bindings.d.ts
- packages/edge-gateway/src/env.js
- packages/edge-gateway/src/error-handler.js
- packages/edge-gateway/src/index.js
- pnpm-lock.yaml
This PR adds logging with loki to the edge gateway.
Needs:
Closes #9
> feat: add loki to edge gateway

- .github/workflows/edge-gateway.yml
- package.json
- packages/edge-gateway/scripts/build.js
- packages/edge-gateway/src/constants.js
- packages/edge-gateway/src/env.js
- packages/edge-gateway/src/error-handler.js
- packages/edge-gateway/src/gateway.js
- packages/edge-gateway/src/index.js
- packages/edge-gateway/src/utils/cid.js
- packages/edge-gateway/test/analytics.spec.js
- packages/edge-gateway/test/cdn.spec.js
- packages/edge-gateway/test/index.spec.js
- packages/edge-gateway/test/utils/miniflare.js
- packages/edge-gateway/wrangler.toml
- packages/ipfs-gateway-race/lib/index.js
- pnpm-lock.yaml
wrangler needs no_bundle = true or else its using its own bundling thing....
> fix: sentry stack traces

- packages/edge-gateway/src/gateway.js
This PR adds dotstorage layer of resolution. It receives multiple hosts via a JSON property `onlyIfCachedGateways` in request.cf object.
This enables us to provided nftstorage.link when requests to w3s.link and the opposite.
Closes #15 
In the future, we can consider:
- add dagula gateway
- make it parallel with 3rd resolution layer (making the 3rd fully aborted if second resolves
> feat: dotstorage layer only if cached

- packages/edge-gateway/wrangler.toml
Same as https://github.com/nftstorage/nftstorage.link/pull/181
> fix: worker routes with zone id

- packages/edge-gateway/denylist.json
This PR adds reported CID to local denylist
> fix: add cid to local denylist

- packages/edge-gateway/wrangler.toml
> feat: use new pinata dedicated gateway

- packages/edge-gateway/wrangler.toml
> fix: temporary remove pinata

- packages/cid-verifier/README.md
This adds docs README to cid-verifier package
> docs: cid verifier

- packages/cid-verifier/README.md
- packages/cid-verifier/wrangler.toml
Fixes CI for publishing `cid-verifier`
> fix: cid verifier wrangler routes

- packages/edge-gateway/src/gateway.js
Based on https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#etag-response-header we need to properly get resource CID from etag to get resource CID
> fix: handle etag formats to get resource cid

- packages/edge-gateway/src/gateway.js
Wrong return value from https://github.com/web3-storage/reads/pull/58
> fix: return value cid from etag

- packages/cid-verifier/wrangler.toml
Per https://github.com/web3-storage/reads/runs/8303579560?check_suite_focus=true#step:7:29 we need to specify per environment
> fix: cid verifier environment variables

- packages/edge-gateway/wrangler.toml
Stil debugging issue with CF team
> fix: revert pinata gateway removal

- packages/edge-gateway/src/gateway.js
This PR addresses two issues:
- Custom gateway race lib errors like timeout error was not caught on L1 racer. As a consequence, we were not going to L2 racer
- Errors with rate limit from L1 were being proxied to requested without trying L2 racer
> fix: error handling on race

- packages/edge-gateway/README.md
Encoding does not seem to be correct if pasted directly. Piping solves it
> chore: improve docs to set race config secret

- packages/edge-gateway/src/constants.js
- packages/edge-gateway/src/gateway.js
- packages/edge-gateway/test/analytics.spec.js
- packages/edge-gateway/test/index.spec.js
This PR adds tracking layer resolution
> feat: track layer resolution header

- packages/cid-verifier/README.md
- packages/cid-verifier/src/auth.js
- packages/cid-verifier/src/bindings.d.ts
- packages/cid-verifier/src/errors.js
- packages/cid-verifier/src/index.js
- packages/cid-verifier/test/auth.spec.js
- packages/cid-verifier/test/utils/miniflare.js
- packages/cid-verifier/test/verification.spec.js
- packages/edge-gateway/README.md
- packages/edge-gateway/src/bindings.d.ts
- packages/edge-gateway/src/gateway.js
- packages/edge-gateway/test/utils/miniflare.js
> feat: adding basic authentication to cid-verifier

- .github/workflows/cid-verifier.yml
- packages/cid-verifier/src/verification.js
- packages/cid-verifier/test/verification.spec.js
This PR uniforms response for malicious content to become like other IPFS Gateways
> fix: uniform response for malicious content

- packages/edge-gateway/src/errors.js
- packages/edge-gateway/src/gateway.js
- packages/edge-gateway/test/cdn.spec.js
Per @alanshaw 's feedback while working on freeway.
Closes #108
> fix: edge gateway error when only if cached request fails

- packages/denylist/src/denylist.js
> fix(denylist): cache time for allowed resource response

- packages/edge-gateway/src/env.js
- packages/edge-gateway/src/error-handler.js
- packages/edge-gateway/src/gateway.js
- packages/edge-gateway/src/index.js
- packages/edge-gateway/wrangler.toml
we're going to rely on Cloudflare Logpush from here out to retain worker logs - enable that and remove Loki logging
> feat: remove Loki logging
