packages/edge-gateway/package.json
packages/edge-gateway/src/bindings.d.ts
packages/edge-gateway/src/env.js
packages/edge-gateway/src/gateway.js
packages/edge-gateway/src/index.js
packages/edge-gateway/src/utils/cid.js
packages/edge-gateway/test/index.spec.js
pnpm-lock.yaml

This PR adds support for gateway to try to resolve CIDs encoded into more bases than b32 and b58. It includes all the basic bases exported by multiformats module.
`ipfs-core-utils` was added to have a quick way of getting what base decoder we want to try.

feat: support base cid encodings

---

packages/edge-gateway/package.json
packages/edge-gateway/src/bindings.d.ts
packages/edge-gateway/src/constants.js
packages/edge-gateway/src/env.js
packages/edge-gateway/src/gateway.js
packages/edge-gateway/test/analytics.spec.js
packages/edge-gateway/test/cdn.spec.js
packages/edge-gateway/test/index.spec.js
packages/edge-gateway/test/utils/miniflare.js
packages/edge-gateway/wrangler.toml
packages/ipfs-gateway-race/lib/index.js
pnpm-lock.yaml

This PR adds necessary changes to track same metrics we track in nftstorage.link. Either by relying on new headers, or via Cloudflare Analytics Engine per detailed on https://github.com/web3-storage/reads/issues/14
Needs:
Closes #10 #14

feat: metrics

---

.github/workflows/conventional-commits.yml
.github/workflows/cron-denylist.yml
packages/edge-gateway/scripts/README.md
packages/edge-gateway/scripts/cli.js
packages/edge-gateway/scripts/heartbeat.js

Adds cron to sync denylist with badbits
It uses same KV as nftstorage.link, so once we get this in we can stop https://github.com/nftstorage/nftstorage.link/actions/workflows/cron-denylist.yml
Needs:
Closes #27

feat: add cron denylist

---

packages/edge-gateway/wrangler.toml

We now have general purpose CF dedicated gateway.
Once merged and released:

fix: use dag haus cf dedicated gw

---

packages/edge-gateway/src/gateway.js

We were losing status code on worker binding interaction

fix: edge gateway keep status code

---

packages/edge-gateway/wrangler.toml

This is still needed for cron until we get denylist in its own package

fix: edge gateway package denylist binding for cron

---

packages/cid-verifier/src/verification.js
packages/cid-verifier/test/verification.spec.js
packages/cid-verifier/wrangler.toml

We had a staging version of web3.storage flagged as malicious LOL 
```
KEY: bafybeibduzzaiid2wuqznu2qhjcnghv7pwovivzmnbanebxnb5jbuoeyue/google-evaluate
VALUE: {"scores":[{"threatType":"SOCIAL_ENGINEERING","confidenceLevel":"SAFE"},{"threatType":"UNWANTED_SOFTWARE","confidenceLevel":"SAFE"},{"threatType":"MALWARE","confidenceLevel":"LOW"}]}
```
https://bafybeibpzakmpdu472pf55xy7ex3m5snu7quxpl3ewk3dl3cw3j5f2a6pq.ipfs-staging.w3[s.]link/ while if we use a public gateway https://bafybeibpzakmpdu472pf55xy7ex3m5snu7quxpl3ewk3dl3cw3j5f2a6pq.ipfs.dweb.link/ we can see it loads and is the web3.storage website.
So, I bumped the levels to ignore until medium and only flag when:
- HIGH | High confidence that the URI given is risky for this threat type.
- VERY_HIGH | Very high confidence that the URI …

fix: bump google evaluate safe confidence levels

---

packages/edge-gateway/src/gateway.js

If we don't wait until in the background, it looks like the request sometimes is cancelled. So, let's not wait to return to user, but keep worker running in the background

fix: edge gateway should wait until cid verifier

---

packages/cid-verifier/src/index.js

Experienced issues with references of requests mutating on follow up subrequests to worker binding. This was leading into logs and sentry reports with not correct request url and request method.
Cloning request https://developers.cloudflare.com/workers/runtime-apis/request#instance-methods should fix it. It looked in the logs that it does, but will need to test with actual malware to validate logs with the results correctly

fix: cid verifier request clone

---

packages/edge-gateway/src/bindings.d.ts
packages/edge-gateway/src/env.js
packages/edge-gateway/src/gateway.js
packages/edge-gateway/wrangler.toml

This PR makes edge-gateway only use cid-verifier if ENV var is set to do so. This is temporary until we wrap up cid-verifier work, so that we are not blocked on releasing edge-gateway as needed.
Production is disabled, Staging and Test are enabled

feat: edge gateway with cid verifier behind env var

---

packages/edge-gateway/src/gateway.js
packages/edge-gateway/test/cid-verifier.spec.js

Follow up of https://github.com/web3-storage/reads/pull/74 to only send CID

fix: edge gateway to provide only cid to cid provider post

---

packages/edge-gateway/src/bindings.d.ts
packages/edge-gateway/src/env.js
packages/edge-gateway/src/gateway.js
packages/edge-gateway/test/analytics.spec.js
packages/edge-gateway/test/cdn.spec.js
packages/edge-gateway/test/utils/miniflare.js
packages/edge-gateway/wrangler.toml

This PR transforms previous gateway race into a two tier race. This is a cost optimisation decision that makes us use ipfs.io first, making other gateways just usable for failure redundancy.
Other details:
- We still keep tier 1 with ipfs.io only for now, but we might add other gateways to tier 1 (for example free cf-ipfs.com).
- Pinata domain changed based on sporadic errors https://user-images.githubusercontent.com/7295071/188930841-8b153be1-2fcf-4447-8a1b-4f377b8c9af4.png that should be handled later on
- NOTE: This was already added in production on a manual release based on failures on last friday demo
With current work being planned, we will be needing less requests to hit origin servers. Both by enabling [CF Cache Reserve](https://blog.cloudflare.com/introducing-cache-reserve/), …

feat: 2 tier race for edge gateway

---

packages/edge-gateway/src/gateway.js

Looks like public gateways might give us invalid etags with resource CID. We are now validating if CID is correct in denylist, so we must take that into account

fix: public gateways might give us invalid etags

---

packages/denylist/src/env.js
packages/denylist/src/index.js

Part of https://github.com/web3-storage/reads/issues/84 makes denylist not logging to avoid adding millions of unnecessary logs into Loki

fix: denylist not logging requests

---

packages/edge-gateway/src/gateway.js
packages/ipfs-gateway-race/lib/index.js
packages/ipfs-gateway-race/test/index.spec.js
packages/ipfs-gateway-race/test/utils/setup.js
packages/ipfs-gateway-race/types.d.ts

This PR updates `ipfs-gateway-race` lib to support an option to abort specific race contestants on demand. When consumers opt in for `noAbortRequestsOnWinner` they can abort when needed.
In `edge-gateway`, we rely on `ipfs-gateway-race` with `noAbortRequestsOnWinner` because we track TTFB of each gateway. However, as soon as fetch promise of gateway requests is fulfilled we can abort the non winner contestants to not get extra bandwidth consumed. 
Closes #11

fix: abort race contestants when all fulfill

---

packages/cid-verifier/src/index.js
packages/cid-verifier/src/verification.js

Part of https://github.com/web3-storage/reads/issues/84 makes cid-verifier package only log when malware is detected, so that we can act upon it.
cid-verifier package includes denylist routes that will also be dropped after #77 
cc @lanzafame (can't ask you review, sent invitation to join web3-storage org)

fix: cid verifier only logs when malware flagged

---

packages/edge-gateway/src/gateway.js
packages/edge-gateway/test/index.spec.js
packages/edge-gateway/test/utils/miniflare.js

If we abort all the requests abort error will be thrown. We should not abort if all failed and there was no winner

fix: not abort when no winner

---

packages/edge-gateway/README.md
packages/edge-gateway/src/constants.js
packages/edge-gateway/src/env.js
packages/edge-gateway/src/version.js
packages/edge-gateway/test/env.spec.js
packages/edge-gateway/test/utils/miniflare.js
packages/edge-gateway/wrangler.toml

This PR adds support for gateway race configuration via wrangler secret.
To avoid potential issues with setting up invalid secret, we validate and default to hardcoded values if given secret is not a valid one. For better observability, race configuration was added to `GET /version` and invalid values are logged.

feat: add support for gateway race configuration via wrangler secret

---

packages/edge-gateway/README.md
packages/edge-gateway/src/bindings.d.ts
packages/edge-gateway/src/constants.js
packages/edge-gateway/src/env.js
packages/edge-gateway/src/gateway.js
packages/edge-gateway/test/cdn.spec.js
packages/ipfs-gateway-race/lib/index.js

This PR adds to the dotstorage cdn resolution an array of CDN Gateways Race. This enables us to include freeway as part of our resolution before hitting first tier of IPFS gateways race.
Needs:

feat: dotstorage hosts resolution layer

---

packages/edge-gateway/src/gateway.js
packages/edge-gateway/src/utils/cid.js
packages/edge-gateway/test/index.spec.js

Once we get Cache Reserve, we will need a way of mapping back an anchor added to badbits/denylist into a URL we want to purge from cache.
Adding anchors to headers (and consequently logs) enables us to quickly search through logs and get the URL to block
Closes #89

feat: log anchor

---

packages/edge-gateway/src/gateway.js

This PR fixes dotstorage race requests to include original request headers. 
This is currently causing problems when range requests happen for content stored within Freeway, as we end up serving the entire content. Example: `curl -v -r 19602680-19668237 "https://bafybeic4ic4gsd45mejopelizyvsq2ybicumtkmqkr6flm6x6kiwbovrc4.ipfs.w3s.link/webarchive.wacz" | wc -c`

fix: dotstorage race requests should receive original request headers

---

packages/edge-gateway/wrangler.toml

We have it disabled in prod. Let's keep it disabled in staging while we don't perform further tests

fix: disable cid verifier in staging

---

packages/edge-gateway/src/constants.js
packages/edge-gateway/src/gateway.js
packages/edge-gateway/test/index.spec.js
packages/edge-gateway/test/mocks/ipfs.io/get_ipfs#@cid#path.js
packages/ipfs-gateway-race/lib/index.js
packages/ipfs-gateway-race/test/index.spec.js
packages/ipfs-gateway-race/test/mocks/cf-ipfs.com/get_ipfs#@cid.js
packages/ipfs-gateway-race/test/mocks/ipfs.io/get_ipfs#@cid.js

where the request provides `if-none-match` header as a cid etag and it matches the cid requested and there is no path, we have all the info we need to return a "304 not modified".
fix bugs where response.ok is only true for 200-299 response, but we may get 304 from upstream and thats ok too.
see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match
see: https://developer.mozilla.org/en-US/docs/Web/API/Response/ok
fixes: https://github.com/web3-storage/w3link/issues/22
License: MIT
Signed-off-by: Oli Evans <oli@protocol.ai>

feat: fast 304 for `if-none-match` requests

---

packages/edge-gateway/wrangler.toml

Because it is required in denylist cron https://github.com/web3-storage/reads/actions/workflows/cron-denylist.yml

fix: add kv bindings for denylist in edge gateway

---

packages/edge-gateway/src/bindings.d.ts
packages/edge-gateway/src/env.js
packages/edge-gateway/src/gateway.js
packages/edge-gateway/test/cdn.spec.js
packages/edge-gateway/wrangler.toml

Per previous discussion with @dchoi27 , we decided to disable perma cache reads for the time being, in order to reduce the number of worker requests (given there are no active users of this feature).

feat: support perma cache fetch disabled via env var

---

packages/denylist/src/denylist.js
packages/denylist/src/index.js
packages/denylist/test/denylist.spec.js

Send an array of CID strings to check if they are on the denylist. Response is the subset of the array that is on the denylist.
```http
POST /
Content-Type: application/json
["cid1","cid2"]
```
This will be used by e-ipfs to check a batch of cids at once, see: https://github.com/elastic-ipfs/bitswap-peer/pull/215
License: MIT

feat: add batch denylist check

---

.github/workflows/denylist-update.yml
packages/denylist/scripts/cli.js
packages/denylist/scripts/denylist.js

Adds support to update remote denylist using the contents of a file hosted in a given URL.
It enables adding and removing items from the denylist via operation parameter

feat: denylist update remote command and workflow

---

packages/denylist/src/denylist.js
packages/denylist/src/utils/denylist.js
packages/denylist/wrangler.toml

Switch to checking all the items in parallel, and let the platform decide the concurrency.
Drops the time to check 1000 items by an order of magnitude
- cold kv from ~180s to ~10s
- warm kv from ~50s to ~5s
```sh
❯ time curl "http://127.0.0.1:8787/" --json @denylist.post.1000.json
[]
________________________________________________________
Executed in    4.36 secs      fish           external
```
...for obvious reason  of not doing each one sequentially.
License: MIT

feat: batch endpoint check items in parallel

---

.github/workflows/cid-verifier.yml
.github/workflows/cron-denylist.yml
.github/workflows/denylist-update.yml
.github/workflows/denylist.yml
.github/workflows/edge-gateway.yml
.github/workflows/ipfs-gateway-race.yml
DEVELOPMENT.md
README.md
package.json
packages/cid-verifier/README.md
packages/cid-verifier/package.json
packages/denylist/README.md
packages/edge-gateway/README.md
packages/edge-gateway/package.json
packages/ipfs-gateway-race/README.md
packages/ipfs-gateway-race/lib/index.js
packages/ipfs-gateway-race/package.json
packages/ipfs-gateway-race/test/index.spec.js
packages/ipfs-gateway-race/test/mocks/ipfs.io/get_ipfs#@cid.js
pnpm-lock.yaml

Wow we didn't update this repo since Node.js 16.
This PR updates the gihub actions, node, pnpm, wrangler and release please versions.
It also:
* Fixes a bug uncovered by using Node.js 20 - we abort the response of the winning gateway. For some reason on Node.js 16 this doesn't cause `response.text()` to throw but does on Node.js 20.
* Fixes an issue in the tests - smoke was returning 200 status when it should have been returning 500, and the test was incorrectly expecting the wrong number of failures (so it was smothered).
* Fixes repo URLs in READMEs.
* Adds `standard` to the root `package.json` since `lint-staged` (run in the root) uses it and couldn't find it.
* Updates the Cloudflare deployment token name.

chore: update repo

---

packages/edge-gateway/src/constants.js
packages/edge-gateway/src/gateway.js

Makes the requirements for adding to the cache stricter and in accordance with the cloudflare docs.
We only call `waitUntil` if it is possible for the response to be added to the cache. This should reduce errors and potentially worker runtimes.

fix: stricter requirements for cache

---

packages/edge-gateway/package.json
packages/edge-gateway/src/gateway.js
packages/edge-gateway/src/utils/cid.js
packages/edge-gateway/src/utils/verification.js
packages/ipfs-gateway-race/lib/index.js
packages/ipfs-gateway-race/lib/request.js
packages/ipfs-gateway-race/package.json
packages/ipfs-gateway-race/test/index.spec.js
packages/ipfs-gateway-race/test/mocks/fixtures.js
packages/ipfs-gateway-race/test/mocks/ipfs.io/get_ipfs#@cid.js
packages/ipfs-gateway-race/test/mocks/ipfs.io/head_ipfs#@cid.js
packages/ipfs-gateway-race/types.d.ts
pnpm-lock.yaml

This PR uses `@storacha/unixfs-dl` to make ranged requests to big unixfs files in order to not exhaust the upstream worker of CPU time.
Also switches to using the `Link` type for CIDs instead of `string`. This allows us to detect if the CID is using the "raw" IPLD codec.

feat: use big file downloader

---

packages/cid-verifier/src/env.js
packages/edge-gateway/package.json
packages/edge-gateway/src/env.js
pnpm-lock.yaml

This PR adds the `logDataTransformer` callback to the Loki Logging class to filter specific fields in a log.
The `edge-gateway` worker currently produces logs with many unnecessary fields that can be removed to reduce log data size and lower costs. More details can be found in [issue #175](https://github.com/storacha/project-tracking/issues/175).
- Upgraded `@web3-storage/worker-utils/loki` package to the latest version
- Upgraded `toucan-js` to version 3.x for compatibility with `@web3-storage/worker-utils/loki`
- Upgraded `@sentry/cli` to ensure compatibility with `toucan-js`
- Added `logDataTransformer` callback in the Loki Logging constructor for custom log field filtering

refactor: add log field filtering to remove unnecessary metadata
